# Generated by Django 5.0.12 on 2025-05-11 17:11

import django.db.models.manager
import project.documents.proxy_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_chatmessage_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmployeeProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(project.documents.proxy_models.ProxyModelReportMixin, 'users.useremployee'),
            managers=[
                ('proxy_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
