# Generated by Django 5.0.12 on 2025-04-07 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=255, verbose_name='Название')),
                ('url_name', models.CharField(max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Допступный url',
                'verbose_name_plural': 'Доступные url',
            },
        ),
        migrations.CreateModel(
            name='SidebarGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Группа бокового меню')),
                ('icon', models.CharField(max_length=255, verbose_name='Иконка бокового меню')),
            ],
            options={
                'verbose_name': 'Группа бокового меню',
                'verbose_name_plural': 'Группы бокового меню',
            },
        ),
        migrations.CreateModel(
            name='SidebarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('icon', models.CharField(max_length=255, verbose_name='Иконка')),
                ('available_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.availableurls', verbose_name='url')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.sidebargroup', verbose_name='Группа бокового меню')),
            ],
            options={
                'verbose_name': 'Элемент бокового меню',
                'verbose_name_plural': 'Элементы бокового меню',
            },
        ),
        migrations.CreateModel(
            name='SidebarItemChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('icon', models.CharField(max_length=255, verbose_name='Иконка')),
                ('available_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.availableurls', verbose_name='url')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sidebaritem', verbose_name='Элемент бокового меню')),
            ],
            options={
                'verbose_name': 'Элемент бокового подменю',
                'verbose_name_plural': 'Элементы бокового подменю',
            },
        ),
    ]
