# Generated by Django 5.0.12 on 2025-04-08 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebaritemchild',
            name='parent_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.sidebaritem', verbose_name='Элемент бокового меню'),
        ),
    ]
