# Generated by Django 5.0.12 on 2025-04-21 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch'),
        ('users', '0002_remove_user_name_user_first_name_user_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название структурного подразделения', max_length=255, verbose_name='Название структурного подразделения')),
                ('description', models.TextField(blank=True, help_text='Введите описание структурного подразделения', null=True, verbose_name='Описание структурного подразделения')),
                ('branch', models.ForeignKey(help_text='Выберите филиал', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.branch', verbose_name='Филиал')),
                ('parent', models.ForeignKey(blank=True, help_text='Выберите родительский подразделение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.department', verbose_name='Родительский подразделение')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название должности', max_length=255, verbose_name='Название должности')),
                ('description', models.TextField(blank=True, help_text='Введите описание должности', null=True, verbose_name='Описание должности')),
                ('department', models.ForeignKey(help_text='Выберите структурное подразделение', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='users.department', verbose_name='Структурное подразделение')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.position', verbose_name='Должность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
