# Generated by Django 5.0.12 on 2025-05-11 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_position_useremployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=255, verbose_name='Кодовое имя доступа')),
                ('description', models.TextField(verbose_name='Описание доступа')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, to='users.userpermission', verbose_name='Права доступа пользователя'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя роли')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание роли')),
                ('permissions', models.ManyToManyField(to='users.userpermission', verbose_name='Доступы роли')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userrole', verbose_name='Роль пользователя'),
        ),
    ]
